#!/bin/bash

if [ $# -lt 1 ]; then
    echo "expected an argument (build, debug, update-resources, encrypt, decrypt, update-site)"
    exit 1
fi

action=$1

if [ "$action" = "build" ]; then
    docker build -t ansible-terraform-demo --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) .
fi

if [ "$action" = "debug" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh
fi

if [ "$action" = "update-resources" ]; then
    docker run -v "$(pwd):/app" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update_resources
fi

if [ "$action" = "encrypt" ]; then
    docker run -v "$(pwd):/app" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/encrypt
fi

if [ "$action" = "decrypt" ]; then
    docker run -v "$(pwd):/app" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/decrypt
fi

if [ "$action" = "update-site" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update_site "${@:2}"
fi

if [ "$action" = "update" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update "${@:2}"
fi

if [ "$action" = "ansible-playbook-all" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/ansible_playbook_all "${@:2}"
fi

if [ "$action" = "ansible-playbook" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/ansible_playbook "${@:2}"
fi
