#!/bin/bash

if [ $# -lt 1 ]; then
    echo "expected an argument (build, debug, update-resources, encrypt, decrypt, update-site)"
    exit 1
fi

action=$1

if [ "$action" = "build" ]; then
    docker build -t ansible-terraform-demo --build-arg USER_ID=$(id -u) .
fi

if [ "$action" = "debug" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh
fi

if [ "$action" = "update-ssh-config" ]; then
    docker run -v "$(pwd):/app" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update_ssh_config
fi

if [ "$action" = "encrypt" ]; then
    docker run -v "$(pwd):/app" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/encrypt
fi

if [ "$action" = "decrypt" ]; then
    docker run -v "$(pwd):/app" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/decrypt
fi

if [ "$action" = "update" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update "${@:2}"
fi

if [ "$action" = "update-all" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update_all "${@:2}"
fi

if [ "$action" = "update-resources" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update_resources "${@:2}"
fi

if [ "$action" = "update-resources-all" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/update_resources_all "${@:2}"
fi

if [ "$action" = "playbook" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/playbook "${@:2}"
fi

if [ "$action" = "playbook-all" ]; then
    docker run --network host -v "$(pwd):/app" -v "/home/$USER/.ssh/:/home/user/.ssh/" -w "/app/" -it ansible-terraform-demo /bin/sh scripts/playbook_all "${@:2}"
fi