---
- hosts: all
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/local/bin/python
  tasks:
    - name: waiting for hosts to be up
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 1
        timeout: 120
        state: started
      connection: local
