---
- name: download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: extract node exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: move node exporter binary
  command: "mv /tmp/node_exporter-1.2.2.linux-amd64/node_exporter /usr/local/bin/"

- name: create node exporter user
  user:
    name: node_exporter
    system: yes
    shell: /bin/false

- name: set permissions for node exporter binary
  file:
    path: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'

- name: create node exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Documentation=https://prometheus.io/
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target

- name: start and enable node exporter service
  service:
    name: node_exporter
    state: started
    enabled: yes
