---
- import_tasks: get_target_provider.yaml

- import_tasks: create_terraform_dir.yaml

- import_tasks: plan_digitalocean.yaml
  when: target_provider.type == "digitalocean"

- import_tasks: plan_hetzner.yaml
  when: target_provider.type == "hetzner"

- import_tasks: execute_plan.yaml