---
- name: define supported resource types
  set_fact:
    supported_resource_types:
      lxc: proxmox_lxc
      vm: proxmox_vm_qemu

- name: check if each resource type exists
  assert:
    that: item.type in supported_resource_types.keys()
    fail_msg: "resource type {{ item.type }} not supported"
    success_msg: "resource type {{ item.type }} is supported"
  loop: "{{ target_provider_active_resources | list }}"
  loop_control:
    label: "{{ item.name }} (type: {{ item.type }})"

- name: render provider.tf
  template:
    src: "{{ role_path }}/files/providers/proxmox/provider.tf.j2"
    dest: "{{ target_provider_terraform_path }}/provider.tf"

- name: render lxc.tf
  template:
    src: "{{ role_path }}/files/providers/proxmox/lxc.tf.j2"
    dest: "{{ target_provider_terraform_path }}/lxc.tf"

- name: render vm.tf
  template:
    src: "{{ role_path }}/files/providers/proxmox/vm.tf.j2"
    dest: "{{ target_provider_terraform_path }}/vm.tf"