---
- name: install python requirements
  pip:
    state: present
    name: 
      - kubernetes
      - PyYAML
      - jsonpatch

- name: create nginx deployment
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      api_version: apps/v1
      kind: Deployment
      metadata:
        namespace: default
        name: nginx-deployment
      spec:
        replicas: 10
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: nginx
                ports:
                  - containerPort: 80

- name: create nginx service
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      api_version: v1
      kind: Service
      metadata:
        namespace: default
        name: nginx-service
      spec:
        type: NodePort
        selector:
          app: nginx
        ports:
          - protocol: TCP
            port: 30080
            targetPort: 80
            nodePort: 30080