#!/bin/sh

providers=$(cat resources.yaml | yq -r '.providers[].name')
inventories=""

for provider in $providers; do
  inventories="$inventories -i terraform/$provider/inventory.yaml"
done

./scripts/decrypt
$(echo "ansible-playbook$inventories $@")
./scripts/encrypt