#!/bin/sh

providers=$(cat resources.yaml | yq -r '.providers[].name')
selected_provider=$(echo "$providers" | fzf --prompt="Select provider: ")

$(echo "ansible-playbook -i terraform/$selected_provider/inventory.yaml $@")
