#!/bin/sh

path="./terraform/"
if [ -n "$1" ]; then
  path="./terraform/$1/"
fi

echo "decrypting"

find $path -type f ! -path '*/.*' ! -name '.terraform.lock.hcl' | while read -r path; do
    ansible-vault decrypt --vault-id demo@vault $path &>/dev/null
done

echo "decrypting done"