#!/bin/sh
providers=$(cat resources.yaml | yq -r '.providers[].name')
destroy_mode=false

read -r -p "Do you expect to delete resources? [y/N] " response
if [[ "$response" == "yes" || "$response" == "y" ]]; then
    destroy_mode=true
fi

inventories=""

for provider in $providers; do
  inventories="$inventories -i terraform/$provider/inventory.yaml"
done

$(echo "ansible-playbook$inventories $@")